### ISSUE TITLE
Deep-Scrubbing incomplete backups marks them as valid

### ISSUE THREAD

**Issue by olifre** [elemental-lf/benji#10]
Cancelling a differential backup:
```
    INFO: $ /opt/benji/bin/benji -c /etc/benji.yaml backup -s b-2018-12-09T01:22:13+0100 -r /tmp/benji_vmbackup.draxbH -f 7 rbd://rbd/myhost.example.com-disk1@b-2018-12-09T01:22:13+0100 myhost.example.com-disk1
    INFO: Marked version V0000000008 as unprotected.
    INFO: Starting sanity check with 0.1% of the ignored blocks.
    INFO: Finished sanity check. Checked 3 blocks {2, 3, 4, 5, 6, 2462, 2335, 546, 115, 127}.
    INFO: Active transforms for storage vmbackup: zstd (zstd).
    INFO: Backed up 3/568 blocks (0.5%)
    INFO: Backed up 6/568 blocks (1.1%)
    INFO: Backed up 9/568 blocks (1.6%)
    INFO: Backed up 12/568 blocks (2.1%)
    INFO: Backed up 15/568 blocks (2.6%)
    INFO: Backed up 18/568 blocks (3.2%)
^C WARNING: IO backend closed with 549 outstanding read jobs, cancelling them.
 WARNING: Storage backend closed with 15 outstanding write jobs, cancelling them.
^C   ERROR: 
```
yields an invalid backup as expected. Running `deep-scrub` marks that as valid, however:
```
    INFO: $ /opt/benji/bin/benji -c /etc/benji.yaml deep-scrub V0000000008
 WARNING: Version V0000000008 is already marked as invalid.
    INFO: Active transforms for storage vmbackup: zstd (zstd).
    INFO: Deep scrubbed 3/463 blocks (0.6%)
    INFO: Deep scrubbed 6/463 blocks (1.3%)
    INFO: Deep scrubbed 9/463 blocks (1.9%)
    INFO: Deep scrubbed 12/463 blocks (2.6%)
<...>
    INFO: Deep scrubbed 453/463 blocks (97.8%)
    INFO: Deep scrubbed 456/463 blocks (98.5%)
    INFO: Deep scrubbed 459/463 blocks (99.1%)
    INFO: Deep scrubbed 462/463 blocks (99.8%)
    INFO: Deep scrubbed 463/463 blocks (100.0%)
    INFO: Marked version V0000000008 as valid.
    INFO: Deep scrub of version V0000000008 successful.
```
Interestingly, the number of blocks is different. 

Removing that backup version yields a warning about missing metadata, though:
```
benji rm -f V0000000008
    INFO: $ /opt/benji/bin/benji -c /etc/benji.yaml rm -f V0000000008
    INFO: Active transforms for storage vmbackup: zstd (zstd).
 WARNING: Unable to remove version V0000000008 metadata from backend storage, the object wasn't found.
    INFO: Removed backup version V0000000008 with 2560 blocks.
```
Maybe `deep-scrub` is missing a metadata validity check?

**Comment by elemental-lf** [comment]
Hmm, we've got three different things: two easy ones and one that will require some thought.
* The number of blocks is different because in the backup case all blocks including sparse and unchanged ones are counted. In the scrub case only non-sparse blocks are counted as there is nothing to check for non-existing sparse blocks.

* The message about the version metadata relates to the version metadata backup which is written at the end of a successful backup. There is no such metadata backup in case of an interrupted backup. I've clarified the message a bit to make it clearer that it refers to the version metadata _backup_.

* The last one is a little bit harder and requires some history: Originally once a version was marked as invalid it would stay invalid and a deep-scrub would have terminated before checking anything because of this. I changed this behaviour so that any transient failures which led to a version being marked invalid could be healed with another deep-scrub after the reason for the transient failures was repaired. But in your case the deep-scrub has no information about the fact that the backup was incomplete and marks the version as valid because all already backed up blocks in the incomplete backup are okay. This is dangerous and needs to be fixed. So maybe we need another boolean flag ("complete") in the version table. But this would lead to an undefined state for valid == True and complete == False. So maybe valid needs to be converted to a enum state field like: 
  - INCOMPLETE
  - COMPLETE_VALID
  - COMPLETE_INVALID

@olifre, what are your thoughts an this? Any better ideas?

**Comment by olifre** [comment]
Thanks for the explanations! I really like that `deep-scrub` can re-mark backups as `valid`, that would be especially helpful if a bug / temporary error on the underlying storage has otherwise invalidated the backups. 

Yes, the enum state seems like the best solution then. It's the only clean way I can think of to communicate the three different states at one glance for the user. 

I am not sure yet about the best naming. Maybe it would be easier to have:
- INCOMPLETE
- VALID
- INVALID

This ensures that whatever other kind of possible state is added in the future (one never knows...), `VALID` can always stay named `VALID` and external tools / users could rely on that. What do you think?

**Comment by elemental-lf** [comment]
Okay, I've made the switch from valid flag to status. I decided against a real database side enum because there are some strings attached regarding portability of enums between different database dialects. I've invested some time into the database migration mechanism. You need to initiate the migration with `benji database-migrate`.
Please give me some feedback on the original reason for this issue, too. Hopefully `benji` will now behave as expected.

**Comment by olifre** [comment]
>  I decided against a real database side enum because there are some strings attached regarding portability of enums between different database dialects

That'a very good point. Indeed I remember that PostgreSQL enums are vastly different than others, so that seems like a wise choice to me :wink:. 
I've migrated the DB and adapted our scripts (e.g. a script letting us know if invalid backups exist) to the new status variable. 
Since I am on holiday tomorrow (or rather, today - but just for a day) I'll come back to reproduce of the original issue later this week. 
But already now, thanks a lot!

**Comment by elemental-lf** [comment]
> I've migrated the DB and adapted our scripts (e.g. a script letting us know if invalid backups exist) to the new status variable.

You can filter on the new status column by using a string comparison like so `status == "valid"`. The database migration isn't perfect by the way, for example the new check constraint for the status column is missing in SQLite. SQLite also has some other interesting behaviour regarding SQL DDL. For a long-term installation I'd still recommend a move to PostgreSQL.

**Comment by olifre** [comment]
> You can filter on the new status column by using a string comparison like so `status == "valid"`.

Yes, that's exactly what I'm doing, it works very vell. Our "invalid" check now just checks `status != "valid"` and sends us a mail with the output of `benji ls 'status != "valid"'`if that returned something. 



> The database migration isn't perfect by the way, for example the new check constraint for the status column is missing in SQLite. SQLite also has some other interesting behaviour regarding SQL DDL. For a long-term installation I'd still recommend a move to PostgreSQL.

I agree. For now we don't want to add additional components to our backup, but we will keep that in mind for the future. 
A way to implement the check in a way compatible with SQLite and any other DBMS could be to have the "enum" in a dedicated table (that just contains the number and the string as columns) and use a foreign key constraint. Using more "plain" SQL instead of the very helpful checks more full-fledged DBMSes offer often help for compatibility. But of course that complicates all queries since to access the "status string" you have to join the status mapping table. So I fully understand your statement that one should move to PostgreSQL (we also use it for anything "of scale", but since our PostgreSQL cluster with pgool is still work in progress, we want to keep the backup separate for now). 



>  Please give me some feedback on the original reason for this issue, too. Hopefully `benji` will now behave as expected.

I tested it just now, and it does!
This is exactly what I was looking for:
```
# benji batch-deep-scrub
    INFO: $ /opt/benji/bin/benji -c /etc/benji.yaml batch-deep-scrub
    INFO: Scrubbing version V0000000001 with name test-vm.example.com-disk1.
   ERROR: Version V0000000001 cannot be deep-scrubbed, it has a status of incomplete.
    INFO: Scrubbing version V0000000002 with name test-vm.example.com-disk1.
   ERROR: Version V0000000002 cannot be deep-scrubbed, it has a status of incomplete.
   ERROR: One or more version had scrubbing errors: V0000000001, V0000000002.
```
Very nice :smile:. 
With this, I think the issue can be closed.

**Comment by elemental-lf** [comment]
Thank you for testing, Oliver! I'll close the issue.
