### ISSUE TITLE
deep-scrub sometimes fails with error 'unknown encoding: idna'

### ISSUE THREAD

**Issue by MannerMan** [elemental-lf/benji#101]
**Describe the bug**

Sometimes when running benji deep-scrub, we get a failure with the error `unknown encoding: idna`. Simply trying deep-scrub again seems to fix the problem. The error appears to occur before the actual deep-scrub begins, i.e. no progress output before it fails.

**To Reproduce**
Currently not able to reproduce consistently, seems to happen at random.

 - benji config: [benji_config.txt](https://github.com/elemental-lf/benji/files/5830065/benji_config.txt)
 - complete error log: [full_benji_error.txt](https://github.com/elemental-lf/benji/files/5830066/full_benji_error.txt)
 - command: We grab the latest backup id in our script and run deep scrub against it like so;
```
#get latest backup id
backup_uuid=$(/usr/local/bin/benji -m ls 'labels["server"] == "dev-pg-f3c002-db003"' | jq -r '.versions | last .uid')

#Perform a deep scrub against our snapshot (checksum verfies all blocks in s3 against snapshot)
echo "running benji deep scrub"
/usr/local/bin/benji deep-scrub --source file:///dev/vg_pgsql/benji_snap ${backup_uuid}
```
- Debug log: I have enabled debug log now and should have additional log information the next time the issue occurs, if needed.

**Expected behavior**

deep-scrub should succeed.

**Platform and versions (please complete the following information):**

 - Linux distribution name and version
   CentOS 8.3 x86_64
 - Benji version (output of `benji version-info` or git commit digest/branch if applicable)
```
    INFO: Benji version: 0.13.0.
    INFO: Configuration version: 1.0.0, supported >=1,<2.
    INFO: Metadata version: 3.0.0, supported >=1,<4.
    INFO: Object metadata version: 2.0.0, supported >=1,<3.
```
 - the output of `python -V` and `pip list` from the same (virtual) Python environment that Benji runs in
We have built a pyinstaller binary for benji using Python 3.8.7 built from source. I ran the following in the docker container we use to build the binary.
```
[appuser@1e8dbeb2e69a benji]$ python3.8 -V
Python 3.8.7

[appuser@1e8dbeb2e69a benji]$ pip3.8 list 
Package                   Version    Location
------------------------- ---------- ----------
alembic                   1.4.3
altgraph                  0.17
argcomplete               1.12.2
benji                     0.13.0     /benji/src
boto3                     1.16.48
botocore                  1.19.48
Cerberus                  1.3.2
colorama                  0.4.4
dateparser                0.7.6
diskcache                 5.1.0
jmespath                  0.10.0
Mako                      1.1.3
MarkupSafe                1.1.1
pip                       20.2.3
prettytable               0.7.2
psycopg2-binary           2.8.6
pycryptodome              3.9.9
pyinstaller               4.1
pyinstaller-hooks-contrib 2020.11
pyparsing                 2.4.7
python-dateutil           2.8.1
python-editor             1.0.4
pytz                      2020.5
regex                     2020.11.13
ruamel.yaml               0.15.100
s3transfer                0.3.3
semantic-version          2.8.5
setproctitle              1.2.1
setuptools                49.2.1
six                       1.15.0
sortedcontainers          2.3.0
sparsebitfield            0.2.3
SQLAlchemy                1.3.22
structlog                 20.2.0
tzlocal                   2.1
urllib3                   1.26.2
zstandard                 0.15.1
```

**Additional context**
We run benji against a local minio s3 service, with a HAproxy in-front for load-balancing and TLS termination.
Further implementation/setup details can be found in issue #97

Please let me know if I can provide additional details.

**Comment by elemental-lf** [comment]
* The problem seems to be in the `botocore` package which is a dependency of the `boto3` package. So as the first point of action I'd suggest to update `boto3` to the latest version which is `1.16.57` and to see if this helps.

* I searched both the issues of `botocore` and `boto3` for `idna` and `encoding` but couldn't find anything that directly matches and I haven't seen this error in my own installations of Benji which are also using S3 storage. There was a hint that the error might by related to URL length. Google revealed the suggestion to import `encodings.idna` and I think that it couldn't hurt to simply try this. I'd suggest to add `import encodings.idna` to the other imports in `src/benji/storage/s3.py`. I'd put it before the `boto3` import but I think that it shouldn't matter.

Please try the package update first and if that fails try the additional import on top of that, so that it is clear if the import is need to fix this or not. Thanks!

**Comment by MannerMan** [comment]
@elemental-lf Thank you for your input, I have re-built our benji pyinstaller binary and deployed to our development servers. Versions ended up at;
```
boto3                     1.16.58
botocore                  1.19.58
```
Hopefully we'll have no failures this weekend when backups run! But if so, I'll give your other suggestion a go. I'll report back next week with the results, thanks!

**Comment by MannerMan** [comment]
@elemental-lf 
Still had a few scrub failures this weekend unfortunately, but at least I now have a full debug log output available;
[benji_scrub_fail.txt](https://github.com/elemental-lf/benji/files/5864753/benji_scrub_fail.txt)
Turns out the scrubbing process does actually start and it gets going a little bit before failing.

I'm going to attempt the import-fix now!

**Comment by elemental-lf** [comment]
@MannerMan thanks for the update. I'll have a look at the debug output soon.

**Comment by elemental-lf** [comment]
I looked into the debugging output and I really think the problem lies with `boto3` or an interaction of your S3 storage with `boto3`. Could you remind me what kind of S3 storage you're using? Is was Ceph, wasn't it? I tried the Ceph bug database just now but didn't come up with a promising match.
So the only course of action would be to work around this and implement our own retry logic... yuck! If a retry would actually show a different result, that is. But before even considering this I'd like to point you to the latest commits on the `master` branch. I switched to a new retry handler in `boto3` which is advertised in the documentation as handling more error cases. I'd be curious if that changes anything for you.

**Comment by MannerMan** [comment]
@elemental-lf 
We're using https://min.io as our S3 storage solution right now, but will probably switch over to netapp storagegrid at some point.
As a side note, we have had this exception occur on a few benji restore operations as well now. Simply running the restore again fixes the issue.

I'll compile a new pyinstaller build from master and give your latest code a go; I'll report back the results as soon as I have something, thanks!

**Comment by MannerMan** [comment]
@elemental-lf 
Fairly sure the code in master-branch has solved this issue. I ran 100 recovery operations with a build from master (`Benji version: unknown+gec8b964`) with no failures. I then reverted back to `Benji version: 0.13.0` and ran the same 100 recovery operations again; 6 failed with the 'encodings.idna' error.

I will deploy the new binary built from master branch to all systems, and if all backup and deep-scrub jobs succeed this weekend I think we can close this issue by monday :)

**Comment by elemental-lf** [comment]
@MannerMan thanks for the update and the good news.

**Comment by MannerMan** [comment]
@elemental-lf No benji failures this weekend! :partying_face:  This issue can be closed I think. Will these fixes make it into a release branch anytime soon? Thank you for for such quick assistance with this issue!

**Comment by elemental-lf** [comment]
I'll try to make a release soon but it will take some time as I need to migrate away from Travis CI first.

**Comment by MannerMan** [comment]
@elemental-lf No problem, thanks again! :star2:
