### ISSUE TITLE
Multiple storages configuration, defaultStorage doesn't quite do what it seems

### ISSUE THREAD

**Issue by aletus** [elemental-lf/benji#105]
Hi all,

I lost pretty much all of my benji backups today, mostly due to misunderstanding of how Benji works underneath the hood.  

The documentation definitely needs more clarification on how defaultStorage supposed to work though and the code needs more logging to be clear where it is writing the files.

I'm looking for ways to salvage as much as I can, so any advice is appreciated.

My original benji setup was with one local storage, storage-1 with defaultStorage set to storage-1.  I'm backing up ceph rbd images using the included ceph script but I don't think it matters in this case.

Everything was working well but was running low on disk space on storage-1 so I planned to migrate the backup to different local storage.   I reread the documentation to figure out how to do this and saw that the benji supports multiple storages.   The documentation explicitly state in backup section  "Destination storage (if unspecified the default is used)"

So my strategy was to rsync storage-1 database and blocks to storage-2, add storage-2 to benji configuration, switch defaultStorage to storage-2 and switch databaseEngine file location to storage-2.

I kept storage-1 configuration in the benji.yaml to easily revert back if issues occurs, but ASSUMED that once defaultStorage is set to storage-2 it would start backing up to storage-2 since I don't specify storage in the backup command so it should use the default one (!).

Everything SEEMED to work after the switch.  New backup was fine, scrub is good, cleanup no problem.  I check the new location for the database sqlite file and it is updating.   

I left the configuration in place for a month or two to build trust in the system.  Everything went fine during that time, backup, scrub, cleanup, etc... 

Finally it is time to cleanup and finish the migration.  Today I went in and remove files from storage-1 and remove it from the configuration.  

Everything broke and I lost all my backups.  

Upon investigation, my assumptions about defaultStorage were wrong.  Benji in the last few months still backup data to storage-1 even though defaultStorage is set to storage-2 and I don't specify destination storage  on the backup command.  Only the database sqlite is updated on storage-2.

Deep dive into sqlite database shown that every version is actually attached to a storage id and every version I have only have storage id 1. I didn't check but from observation seems that the ceph rbd backup just **continue to create new versions with the same storage id even though defaultStorage was changed**.

And I cannot just delete storage-1 from the configuration either, since the storage id 1 is map to storage-1 inside the database not just the first item in the configuration.  So I need to rename the configuration entry of storage-2 to storage-1 or do some editing of sqlite table, ie **can't just delete storage configuration because it is still referenced in the database.**

In hindsight, I was too careful and it backfired. I probably would saved me a lot of trouble if I just edited the path of storage-1 to storage-2 after rsync. Trying to keep multiple storage configurations for reverting was the source of the issue.

So now how to salvage what is left?  I cannot recovered the blocks from storage-1 that I removed today but I still have the original rsync blocks from storage-1 to storage-2 from a few months although most of it is probably outdated.

The other problem is I did a scrub to test afterward and benji marked a whole bunch of versions as invalid because it couldn't find the blocks.

So if I edit the configuration pointing storage-1 path to storage-2 path, how do I uninvalid those version and recheck what I actually have left?

Also how to do I cleanup the dangling blocks  that may not be referred in the database anymore.

Thanks

**Comment by aletus** [comment]
The list command shown that there is exactly one version before the date which I rsync from storage-1 to storage-2.    All other versions are after that date, which I assume is completely gone since they were still written to storage-1 and I nuked that already.

At this point it is probably best just to start over with a fresh database and new backup. 

But in the interest of education is it possible to "uninvalid" that version, remove all the other versions since that point and clean up any dangling unreferenced blocks.   I would like to have a least that one backup version that works for restore if need to.

Thanks

**Comment by elemental-lf** [comment]
I'm really sorry that this happened to you.

Benji will use the storage of the base version if any is specified on the command line of the `benji backup` command because the new version will potentially reference blocks of the base version and I decided that all the blocks of one version must be in one storage. This design choice prevents versions which are scattered across multiple storages and was actually meant to reduce confusion and it also makes it possible to actually decommission old storages in a timely manner. Benji  terminates itself if the storage of the base version and the storage specified on the `benji backup` command line do not match:

https://github.com/elemental-lf/benji/blob/ec8b964aa82a025a938ff112e50c8270b4f55379/src/benji/benji.py#L95-L96

But as you've found out this check doesn't trigger if the default storage is used.

So what would have been the best cause of action in a migration scenario such as yours:

* Either move the database and the blocks on the filesystem level and just adjust the paths in Benji's configuration. This way there still would be only one storage and deduplication would take into account the blocks of all old backups.
* Or add an additional storage, change the configuration to use the new storage and run one backup without specifying a base version. This way a completely new backup would be created on the new storage that doesn't depend on any of the old backups. But you would need to keep the old storage and storage configuration around until all old backups would have aged out or would've been removed by hand.

What you actually did is a mixture of both I think.

In reference to your last message: Yes, I'd assume that all the backups between your rsync and now are gone. Backups before that would still be available if you pointed the old storage to the new path even if they have been marked as invalid. Benji will tell you during the restore if any of the blocks had problems. There is no option to recheck blocks and versions and mark them as valid again, this process is one-way only at current (valid -> invalid).

I'm going to do several thing as a result of this issue:

- Ensure that Benji always errors out if the base version's storage doesn't match the storage that would've been taken if no base version was specified. This should catch your case.
- Add a kind of revalidation option to Benji`s deep-scrubbing process so that invalid versions could be rechecked. Marking blocks that have become available again as valid and also marking a version as valid if all of its blocks are valid again.
- Add a note to the documentation about the fact that the base version implicitly sets the storage of any new versions based on it.

I'm not sure if I've addressed all your points, so please ask if anything is still unclear.

**Comment by aletus** [comment]
Thank you for getting back to me.  Your explanation is very clear.  

I'm using the ceph backup bash script included in the distribution and that took care of the snapshot and differential backup so I never paid attention to a "new" base backup vs an incremental.  I guess I can delete the automate snapshot and force a "new" backup.

To help other avoid my issue, please  add to documentation a mini how to migrate storage guide, basically the two bullet points you wrote above.

Please also add explicit logging message of where benji is writing the backup blocks and versions.  Something along the line of "Writing backup files and blocks to storage-1, path /xyz...".

In regard to recovery my backup, good to know that even though the version is invalid a restore would still work.  How would I clean up the dangling blocks and versions, ie the rsync data had a lot of older versions that has since been removed and cleanup.  Would the regular cleanup detect the unreferenced blocks and versions and remove that?

**Comment by elemental-lf** [comment]
> Please also add explicit logging message of where benji is writing the backup blocks and versions. Something along the line of "Writing backup files and blocks to storage-1, path /xyz...".

I will add a message explicitly stating the storage the backup is being written to. But in your case the backup will also terminate with an error in the future if the used and the expected storage don't match up.

> In regard to recovery my backup, good to know that even though the version is invalid a restore would still work. How would I clean up the dangling blocks and versions, ie the rsync data had a lot of older versions that has since been removed and cleanup. Would the regular cleanup detect the unreferenced blocks and versions and remove that?

No, unfortunately not. A simple version is not too hard to implement but it would be a really expensive operation which depending on the backup volume could take hours or days and no backups could be taken in the meantime. I will put some thought into this but don't hold your breath. The single source of truth for the blocks and versions is the database.

**Comment by aletus** [comment]
That is alright if it is not possible to remove the unreferenced blocks and versions at this point.  After I get backups going again with a fresh start and get a couple versions in, I will wipe entire the previous rsynced data.

Although not a priority,  I would say there is value in either an external tool or built in cleanup of unreferenced files, even though it may be expensive operation.  Eventually some errors or disruption of clean up may leave unreferenced files accumulating over time.

Would you like me to close this issue or keep it open until you close it?

Thanks

**Comment by elemental-lf** [comment]
Let's keep this open for a little longer. I'd like to implement at least some of the simpler parts that we worked out first.

**Comment by elemental-lf** [comment]
> I'm going to do several thing as a result of this issue:
> 
>     * Ensure that Benji always errors out if the base version's storage doesn't match the storage that would've been taken if no base version was specified. This should catch your case.
> 
>     * Add a kind of revalidation option to Benji`s deep-scrubbing process so that invalid versions could be rechecked. Marking blocks that have become available again as valid and also marking a version as valid if all of its blocks are valid again.
> 
>     * Add a note to the documentation about the fact that the base version implicitly sets the storage of any new versions based on it.

I've addressed bullet points 1 and 3 in the current `master` branch. The second one will take more time but a scenario such as yours should hopefully not repeat itself. I'm going to close this issue.

**Comment by elemental-lf** [comment]
@aletus just wanted to let you know that revalidation of blocks and versions is in `master` now: https://github.com/elemental-lf/benji/commit/207bab1511696a51f6029927cd0e400f4e9f6cb8
