### ISSUE TITLE
benji database-init should be called first time running the container

### ISSUE THREAD

**Issue by budimanjojo** [elemental-lf/benji#135]
Hello, I'm using benji-k8s container to backup PVCs. But the database is not initialized from container and I need to do `benji database-init` before I can continue. Shouldn't this be done from the container level when I first started the container?

**Comment by elemental-lf** [comment]
Initializing the database is in general a one time thing for each installation. Benji could check if there already are tables present and initialize the database automatically otherwise. But I wouldn't be comfortable with such an approach as it would mask genuine errors like the situation where the tables were deleted by accident.
