### ISSUE TITLE
Publish to a Helm repository in order to support Terraform deployments

### ISSUE THREAD

**Issue by alexander-bauer** [elemental-lf/benji#146]
**Is your feature request related to a problem? Please describe.**
I'm working on deploying Benji on a fully Terraform-managed K8s cluster using the [helm_release resource](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release). This supports using a chart from a repository or from an artifact URL. Having to first clone the repository introduces a great deal of complication for deployment methodology - it means that either an already-built chart tarball needs to be checked in to LFS in the repository, or that the whole repository needs to be included as a submodule.

**Describe the solution you'd like**
Please publish the Helm chart to a repository, [such as with GitLab pages](https://medium.com/@mattiaperi/create-a-public-helm-chart-repository-with-github-pages-49b180dbb417).

**Describe alternatives you've considered**
Instead of using a repository, it could be feasible to build the chart and publish it as an artifact as part of each tagged release, but this would not be as broadly applicable, and perhaps just as complicated.

**Comment by alexander-bauer** [comment]
I've created PR #147 to address this.

**Comment by elemental-lf** [comment]
Thank you for your contribution. It's a great addition! I've been using `helmfile` for a long time and it has the ability to directly download charts from git repositories which is why I had no need for a helm repository yet. I've made some changes to your PR:

- Renamed the helm chart from `benji-k8s` to `benji`, something I wanted to do for quite some time
- Updated chart dependencies
- Relocated the helm repository index to `/helm-charts/index.yaml` so that there can be no confusion with the main page and it also would make a possible to add a specific `index.html`  with pointers on how to use the repository if people access the helm repository via their normal browser
- Renamed the chart releases so that there is no confusion with normal Benji releases, especially now that the chart is called `benji`
