### ISSUE TITLE
incomplete backup can't be removed

### ISSUE THREAD

**Issue by blodone** [elemental-lf/benji#24]
When a backup is incompleted caused by a killed process / power outage etc. like this here
```
| 2019-02-04T23:48:03 | V0000000007 | RBD-2810875e-ba27-4ccf-b802-96268ac7104e | FREEZE_2019-02-04T19:07:57.864475+00:00 | 120.0GiB |     4.0MiB | incomplete |   False   | file    |
```

trying to remove the backup does not work
```
benji rm -f V7
    INFO: $ /backup/benji/venv/bin/benji rm -f V7
   ERROR: Version V0000000007 is already locked.
```

what would be the way to clean it from the database and the storage?

**Comment by elemental-lf** [comment]
The real reason seems to be not that it is incomplete but that the lock couldn't be cleaned up be Benji because it was killed. Benji tries to cleanup any left-over locks at termination but this won't help when it is killed. I think I'll need to add an option to `rm` to override locks. For the time being you can delete the row from the `locks` table manually.

**Comment by elemental-lf** [comment]
I've just added a CLI option for overriding stale locks to `rm` and `cleanup`. Please see https://github.com/elemental-lf/benji/commit/25bee4a7458c79025df385b325219b996f62bd5e for the implementation. The Docker images (tags `master` and `latest`) will be updated automatically, but it will take some time.

**Comment by blodone** [comment]
thanks, got it tested today and its working like expected ;) good work
