### ISSUE TITLE
Versions and Retention

### ISSUE THREAD

**Issue by adambmedent** [elemental-lf/benji#36]
I was wondering if there is anyway besides using labels to determine what versions are a full backup and what versions are differential?  

Also wondering how retention determines what version to keep in specific scenario's?  For example, if we are keeping 14 daily versions and wanted to keep monthly versions, how does benji determine what daily is the best to keep?  Does it just keep the oldest daily as the monthly?

**Comment by elemental-lf** [comment]
Benji per se has no concept of full or differential backups. When backing up Ceph RBD images it is using the output of `rbd diff` to only look at blocks that have changed since the last backup, i.e. it only looks at the differences. That is the reason why it is called differential in this context. From a restore standpoint all backups are (synthetic) full backups as Benji just gathers all the blocks and assembles them in the right order. It doesn't start from a full backup and then applies the differences.

**Comment by elemental-lf** [comment]
Regarding the retention algorithm please have a look at the documentation. I know that the documentation could be more precise in this area, but I'm having trouble expression the details in English as I just found out again while trying to answer your question. And there actually might be bugs in the algorithm, so any tests and reviews of the algorithm in https://github.com/elemental-lf/benji/blob/master/src/benji/retentionfilter.py  are welcome.
