### ISSUE TITLE
bug mimic? compatibility?

### ISSUE THREAD

**Issue by kayamax** [elemental-lf/benji#5]
solved! error caused due broken mimic package dependencies

**Comment by elemental-lf** [comment]
I think it would be better if you used separate comments, instead of editing one comment. This would make it easier to follow the issue. But I'm glad that you figured it out! 
Please be aware that Benji is still undergoing development. I've been busy with other things for some time, but I have started development again in the background towards a first beta release which will have more compatibility guarantees and be better suited as a base for community interaction and development. There will be incompatible changes to the database and the metadata structure! I think about three months is a realistic time frame for this.
