### ISSUE TITLE
Show storage-stats by volume

### ISSUE THREAD

**Issue by Olvikolvi** [elemental-lf/benji#74]
It would be lovely to have disk usage stats by volume (or/and by label).
Maby something like:
benji -m storage-stats -v vm-100-disk-0
{
    "objects_count": 14724,
    "objects_size": 30862227943
}

**Comment by elemental-lf** [comment]
Hey @Olvikolvi, we had such a feature request before, please see https://github.com/elemental-lf/benji/issues/69#issuecomment-581669198 for my reply.

Of course it would be possible to output _some_ statistics per version or set of versions (grouped by volume for example as you write), but I'm not convinced that they would be meaningful and useful for something due to the nature of storage wide deduplication. 

What is your use case? And would you still consider your use case valid when taking into account storage wide deduplication?

**Comment by Olvikolvi** [comment]
Would like to offer agreed amount of storage space for backups for my customers. So they can choose by VM how long time backups are kept and how often backups are made. Now we just have to give “unlimited” space without knowing how much they are really using it.

**Comment by elemental-lf** [comment]
But the same backup store is used for multiple customers, yes? Let me propose the following idea:

Add a function to calculate space usage over a set of versions
 * that doesn't try to do anything clever about shared blocks
 * but still only counts unique non-sparse blocks towards the space usage.

So, if the set of versions would be comprised of the all versions belonging to one customer we would simulate a backup which does deduplication by customer. I think this would be a fair compromise if properly documented and explained to the customer ("_Dear customer, the space usage is calculated based on the assumption that deduplication of backups is by customer..._"). The space saved by sharing blocks between customers which will probably be significant would be your "win".

The set of versions could be identified by using a label which holds the customer name or number for example. Due to the uniqueness requirement this will be expensive and slow to calculate nonetheless.

**Comment by Olvikolvi** [comment]
Yes this sounds good enough. We only use this for block device (ceph) backups so don't know how much shared blocks exists. But as you said it's just our win.On Apr 14, 2020 1:54 PM, Lars Fenneberg <notifications@github.com> wrote:
But the same backup store is used for multiple customers, yes? Let me propose the following idea:
Add a function to calculate space usage over a set of versions
that doesn't try to do anything clever about shared blocksbut still only counts unique non-sparse blocks towards the space usage.
So, if the set of versions would be comprised of the all versions belonging to one customer we would simulate a backup which does deduplication by customer. I think this would be a fair compromise if properly documented and explained to the customer ("Dear customer, the space usage is calculated based on the assumption that deduplication of backups is by customer..."). The space saved by sharing blocks between customers which will probably be significant would be your "win".
The set of versions could be identified by using a label which holds the customer name or number for example. Due to the uniqueness requirement this will be expensive and slow to calculate nonetheless.

**Comment by elemental-lf** [comment]
Okay, I'll put something like this on my TODO list but don't  hold your breath. If you need something sooner, then I suggest that you go directly to the database and write some SQL statements. It shouldn't be too hard.

**Comment by Olvikolvi** [comment]
Can you explain this values in versions table?
 bytes_read BIGINT, 
 bytes_written BIGINT, 
 bytes_deduplicated BIGINT, 
 bytes_sparse BIGINT, 

Is this correct query for total space usage by volume?
SELECT volume, SUM(bytes_written)+SUM(bytes_deduplicated) FROM versions GROUP BY volume;

**Comment by elemental-lf** [comment]
These columns are statistics gathered during the version creation and refer to that backup run. They are not suitable for this purpose. You need to look for all non-sparse blocks of a set of versions (`uid_left` and `uid_right` are not `NULL`), remove any duplicates (same `uid_left`/`uid_right` pair) and then sum up  their `size`es.

**Comment by elemental-lf** [comment]
The master branch now implements the first draft of the space usage statistics. It is not very well tested yet. If you want to try it out I suggest that you label all your volumes with a customer identifier and then call Benji like `benji storage-usage 'labels["customer-id"] == "12345"'` for each customer. The sum of `deduplicated_exclusive` and `shared` estimates the space used by this customer without
taking into account deduplication effects between customers. The resulting number emulates the case as if each customer would have their own instance of Benji.

**Comment by elemental-lf** [comment]
I'll close this issue. Please report back in a new issues if `benji storage-usage` fits your use case or not. Thanks!
