### ISSUE TITLE
[newbie] please give example of configuration file with compression

### ISSUE THREAD

**Issue by mgiammarco** [elemental-lf/benji#76]
Hi,
I am reading documentation but I do not understand how to build a yaml config file with zstd compression and with 10 threads for rbd.
Benji crashes with an exceptions without telling me the line number with first error.
Thanks in advance for any help.

**Comment by mgiammarco** [comment]
I was able to do it myself:

 configurationVersion: '1'
databaseEngine: postgresql://benji-prod:Password1@postgres:5432/benji-prod
defaultStorage: storage-1
storages:
  - name: storage-1
    storageId: 1
    module: file
    configuration:
      path: /data
      simultaneousReads: 5
      simultaneousWrites: 5
      activeTransforms:
      - zstd-1
transforms:
  - name: zstd-1
    module: zstd
    configuration:
      simultaneousReads: 10
      simultaneousWrites: 10
ios:
  - name: rbd
    module: rbd

But I still do not understand why configuration: does not need a dash (-) and why I cannot avoid formatting above

**Comment by elemental-lf** [comment]
@mgiammarco unfortunately the formatting of the configuration you included is garbled. Please use a code block in the future, so that the formatting is preserved. 
The `configuration` blocks are maps/dictionaries and not lists, so there are no dashes at that  level. The whole configuration is YAML formatted. You can use tools like `yamllint` to check the formatting. Benji will also point out where the problems with the configuration are (like `configuration.storages.0.dmodule: unknown field` or `configuration.storages.0.module: required field`) but you're correct that no line number is currently included in the error messages.
You can also find example configurations in the smoke test: 
https://github.com/elemental-lf/benji/blob/095fc919dd337b37617c5c432879b38d057cb6e1/src/benji/tests/test_smoketest.py#L251-L649
You need to trim the leading white space of course.
